# REMOTE
# alias rmt-instance="ssh -i ~/.ssh/ssh-key.pem ubuntu@X.X.X.X"
alias rmt-r2d2="ssh soriano@r2-d2.local"

# TERMINAL
alias restart='sudo systemctl restart systemd-logind'
alias shutdown='sudo shutdown now'

alias update='sudo apt update && apt upgrade -y'

alias rank='sort | uniq -c | sort -nr | head -n 10'
alias history-command='history | grep'
alias filesize='du -sh * | sort -h'
alias mkdir='mkdir -pv'
alias ips='ip -c -br a'
alias cls='clear'
alias lsa='ls -la --group-directories-first'
alias ls='ls -l --group-directories-first'

alias nvim-open='nvim $(fzf --preview "bat --color=always {}")'

# DOCKER
alias dkc='docker compose'
alias dk='docker'

# KUBERNETS
alias kube='kubectl'
