include ~/.config/omarchy/current/theme/kitty.conf

# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        9.0

# Window
show_window_resize_notification no
hide_window_decorations yes
confirm_os_window_close 0
window_padding_height 14
window_padding_width 14

# Keybindings
map alt+shift+enter send_text all \e[13;4u
map shift+enter send_text all \e[13;2u
map shift+insert paste_from_clipboard
map ctrl+insert copy_to_clipboard

# Allow remote access
allow_remote_control yes
single_instance yes

# Aesthetics
enable_audio_bell no
cursor_shape block

# Minimal Tab bar styling
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
tab_bar_style               powerline
tab_powerline_style         slanted
tab_bar_edge                bottom
