export const BLOQUED_FILES = [
  "google-credentials*.json",
  "firebase-adminsdk*.json",
  "service-account*.json",
  ".docker/config.json",
  ".git-credentials",
  ".gem/credentials",
  "terraform.tfvars",
  "credentials.json",
  "*.tfvars.json",
  "*credentials*",
  ".terraformrc",
  ".gitcookies",
  ".gitconfig",
  "id_ed25519",
  "*.keystore",
  "*password*",
  "id_ecdsa",
  "*.secret",
  "*.tfvars",
  "*secret*",
  "*passwd*",
  ".pypirc",
  ".yarnrc",
  "*.ovpn",
  "id_rsa",
  "id_dsa",
  ".netrc",
  ".npmrc",
  ".env.*",
  ".test",
  "*.env",
  "*.p12",
  "*.pfx",
  "*.crt",
  "*.cer",
  "*.jks",
  "*.pem",
  "*.key",
  "*.p8",
  ".env",
];

export const CONTENT_READING_COMMANDS = ["less", "more", "head", "tail", "grep", "nano", "code", "awk", "sed", "vim", "cat", "rg", "vi"] as const;

export const BLOCKED_CREDENTIALS_PATHS = [
  "~/.local/share/keyrings",
  "~/.config/BraveSoftware",
  "~/.config/google-chrome",
  "~/.config/1Password",
  "~/.mozilla/firefox",
  "~/.config/chromium",
  "~/.password-store",
  "~/.config/gcloud",
  "~/.config/gh",
  "~/.docker",
  "~/.gnupg",
  "~/.azure",
  "~/.kube",
  "~/.ssh",
  "~/.aws",
  "vpn",
];

export const BLOCKED_ROOT_PATHS = ["/etc", "/root", "/var", "/boot", "/proc", "/sys", "/dev", "/run/secrets"];

export const BLOCKED_CONFIGS_PATHS = [
  "~/.config/kubernetes",
  "~/.config/bitwarden",
  "~/.config/1password",
  "~/.config/terraform",
  "~/.config/gcloud",
  "~/.config/azure",
  "~/.config/helm",
  "~/.config/git",
  "~/.config/gh",
];

