# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'right', 'l']
cd_quit = ['Q', '']
quit = ['q', 'esc']

# movement
list_down = ['down', 'j']
page_down = ['pgdown','']
list_up = ['up', 'k']
page_up = ['pgup','']

# file panel control
previous_file_panel = ['shift+left', 'H']
toggle_file_preview_panel = ['f', '']
open_sort_options_menu = ['o', '']
create_new_file_panel = ['n', '']
toggle_reverse_sort = ['R', '']
next_file_panel = ['tab', 'L']
close_file_panel = ['w', '']

# change focus
focus_on_process_bar = ['p', '']
focus_on_metadata = ['m', '']
focus_on_sidebar = ['s', '']

# create file/directory and rename
file_panel_item_create = ['ctrl+n', '']
file_panel_item_rename = ['ctrl+r', '']

# file operations
delete_items = ['ctrl+d', 'delete', '']
paste_items = ['ctrl+v', 'ctrl+w', '']
permanently_delete_items = ['D', '']
copy_items = ['ctrl+c', '']
cut_items = ['ctrl+x', '']

# compress and extract
compress_file = ['ctrl+a', '']
extract_file = ['ctrl+e', '']

# editor
open_current_directory_with_editor = ['E', '']
open_file_with_editor = ['e', '']

# other
copy_present_working_directory = ['c', '']
open_command_line = [':', '']
change_panel_mode = ['v', '']
pinned_directory = ['P', '']
toggle_dot_file = ['.', '']
open_spf_prompt = ['>', '']
open_help_menu = ['?', '']
copy_path = ['ctrl+p', '']
toggle_footer = ['F', '']
open_zoxide = ['z', '']

# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
cancel_typing = ['ctrl+c', 'esc']
confirm_typing = ['enter', '']

# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['h', 'left', 'backspace']
search_bar = ['/', '']

# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['shift+down', 'J']
file_panel_select_mode_items_select_up = ['shift+up', 'K']
file_panel_select_all_items = ['A', '']
